### ISSUE TITLE
s6-log scripts fail to run

### ISSUE THREAD

**Issue by grknight** [tokiclover/supervision-scripts#2]
Please remove the p${LOG_PREFIX} from the s6 log section of sv/.opt/SVC_OPTIONS  it is an invalid token

**Comment by tokiclover** [comment]
Fixed, thanks for reporting.

It's a good thing you're testing with s6 suite because I only test with Runit and seldomly with daemontools-encore. I was pretty sure to have read the related sub-section of multilog(8) and s6-log(8)... but it seems I was too busy with other things to have missed it.

**Comment by tokiclover** [comment]
One last thing... off topic: Any thought on the default for getty/s6?

**Comment by grknight** [comment]
Currently, getty fails to run due to "for file in "${SVC_CONFIGFILE}" ${SVC_REQ_FILES}; do" in svc_pre() at sv/.opt/supervision-functions coming up empty.  Since there is no -n test, ! -f kills the service. Adjusted locally and it seems to work.    Other than that, not sure what you mean by "the default".

**Comment by tokiclover** [comment]
Ah my fault, the quote cause an empty loop... so removed. Hopefully, this was not in r17, so waiting for enough material for r18.

I mean, I'd like to have at least an `utmpset` like thing to log successful tty, but there is nothing of the sort with s6.
